//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite_SaleManagement_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsPhieuNhap
    {
        public int DetailsCodePN { get; set; }
        public Nullable<int> PNCode { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<decimal> Import_Unit_Price { get; set; }
        public Nullable<int> Quantity_Of_Goods_Imported { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual Product Product { get; set; }
    }
}
