//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite_SaleManagement_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailsCode { get; set; }
        public Nullable<int> OrderCode { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> NumberOfOrders { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
