//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite_SaleManagement_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.DetailsPhieuNhaps = new HashSet<DetailsPhieuNhap>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductCode { get; set; }
        public string NameProduct { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string Configuration { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal intoMoney { get; set; }

        public Nullable<int> InventoryNumber { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> Votes { get; set; }
        public Nullable<int> Comment { get; set; }
        public Nullable<int> NumberOfPurchases { get; set; }
        public Nullable<int> NewProduct { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public Nullable<int> ManufacturerCode { get; set; }
        public Nullable<int> ProductTypeCode { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsPhieuNhap> DetailsPhieuNhaps { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
